sudo: required
services:
  - docker

after_success:
 — docker build -t sjryall/multi-server ./server
 — docker build -t sjryall/multi-client ./src

 — echo “$DOCKER_PASSWORD” | docker login -u “$DOCKER_ID” — password-stdin

 — docker push sjryall/multi-server
 — docker push sjryall/multi-client