version: "3"

services:
  server:
    build: ./server
    image: sjryall/node-server
    expose:
      - 8000
    environment:
      - API_HOST="http://0.0.0.0:3000/"
      - APP_SERVER_PORT=8000
      - NODE_ENV=production
    volumes:
      - ./srv/app/test-app-server/node_modules
      - ./server:/srv/app/test-app-server
    ports:
      - 8000:8000

    command: npm run dev-server
  src:
    build: ./src
    image: sjryall/node-src
    environment:
      - REACT_APP_PORT=8080
    volumes:
      - ./srv/app/test-app-src/node_modules
      - ./src:/srv/app/test-app-src
    expose:
      - 8080
    ports:
      - 8080:8080
    links:
      - server
    command: npm run dev-client
